#!/bin/bash

function installWP {
	echo "::: INSTALLING WORDPRESS :::"
	wget -O ./wp.tgz http://wordpress.org/latest.tar.gz
	if [[ "$?" != "0" ]]
	then
  		echo "an error happened downloading WordPress!"
  		exit 1
	fi
	
	salts="`wget -qO- https://api.wordpress.org/secret-key/1.1/salt/`"
	if [[ "$?" != "0" ]]
	then
  		echo "an error happened getting random salts!"
  		exit 1
	fi
	
	tar xf ./wp.tgz
	mv ./wordpress/* .
	rmdir ./wordpress
	rm ./wp.tgz
	cat ./templates/wp-config.php | sed -e "s/\${db_name}/$1/" -e "s/\${project_name}/$1/" | sed  '45d' | sed "45i $(echo $salts | sed -e 's/[\/&]/\\&/g')" > ./wp-config.php
	 
}

function installEdenticBaseTheme {
	echo "::: INSTALLING EDENTIC BASE THEME :::"
	wget -O ./basetheme.zip https://github.com/Edentic/EdenticBaseTemplate/archive/master.zip
	if [[ "$?" != "0" ]]
	then
  		echo "an error happened downloading Edentic Base Theme!"
  		exit 1
	fi
	
	unzip ./basetheme.zip -d ./wp-content/themes/$1
	mv ./wp-content/themes/$1/EdenticBaseTemplate-master/* ./wp-content/themes/$1
	rmdir ./wp-content/themes/$1/EdenticBaseTemplate-master
	rm ./basetheme.zip
}

function setDBSettings {
		echo "::: SETTING UP DATABSE :::"
		cat ./templates/settings.pp | sed -e "s/\${db_name}/$1/" > ./manifests/settings.pp
}

function startVagrant {
	echo "::: STARTING VIRTUAL ENVOROMENT :::"
	vagrant up
	if [[ "$?" != "0" ]]
	then
    	echo "Vagrant could not start! Have you installed vagrant?"
  		exit 1
  	fi
}

case $1 in
	"init")
            if [ "$2" = "" ]; 
            then
                echo No project name given!;
            else
                setDBSettings $2;
                startVagrant;
            fi
	;;

	"WPinit")
            if [ "$2" = "" ]; then
                echo No project name given!
            else
				installWP $2;
				if [[ "$?" != "0" ]]
				then
  					echo "WordPress could not be installed!"
  					exit 1
				fi

				if [[ "$3" == "incbasetheme" ]]
				then
					installEdenticBaseTheme $2
				fi

				setDBSettings $2;
				startVagrant;
			fi
	;;

	*)
		echo "Please do init for setting up vagrant or WPinit for installing wp and setting up vgrant"
	;;
esac




